# Generated by Django 6.0.5 on 2026-09-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printing', '0008_attributedefinition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='printing.labeltemplate', verbose_name="Template d'impression par défaut")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'printing_category',
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la caractéristique')),
                ('data_type', models.CharField(choices=[('NUMBER', 'Nombre décimal ou entier (ex: 50, 42.5)'), ('INTEGER', 'Nombre entier strict (ex: 500, 12)'), ('CHOICE', 'Liste déroulante / Choix fermé (défini dans options)'), ('TEXT', 'Texte libre'), ('BOOLEAN', 'Oui / Non')], default='NUMBER', max_length=20, verbose_name='Type de donnée')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unité (ex: cm, µm, mm, kg)')),
                ('options', models.CharField(blank=True, help_text='Pour les listes de choix, séparez par des virgules (ex: PEBD, PEHD, PP, CPP)', max_length=500, null=True, verbose_name='Options autorisées')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Définition de caractéristique',
                'verbose_name_plural': 'Définitions de caractéristiques',
                'db_table': 'printing_attributedefinition',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Symbole (ex: kg, U)')),
                ('input_mode', models.CharField(choices=[('STANDARD', 'Standard (Quantité simple)'), ('WEIGHT', 'Poids (Demander le poids)'), ('PACK_COUNT', 'Conditionnement (Unités par carton)')], default='STANDARD', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'db_table': 'printing_unit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Référence / SKU')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Catégorie')),
                ('custom_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_products', to='printing.labeltemplate', verbose_name='Template spécifique (écrase celui de la catégorie)')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'printing_product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255, verbose_name='Valeur')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributedefinition', verbose_name='Caractéristique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Caractéristique du produit',
                'verbose_name_plural': 'Caractéristiques du produit',
                'db_table': 'printing_productattributevalue',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
