# Generated by Django 6.0.5 on 2026-05-18 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du modèle')),
                ('zpl_code', models.TextField(verbose_name='Code ZPL')),
            ],
            options={
                'verbose_name': "Modèle d'étiquette",
                'verbose_name_plural': "Modèles d'étiquettes",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='printing.labeltemplate', verbose_name="Template d'impression par défaut")),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Symbole (ex: kg, U)')),
                ('input_mode', models.CharField(choices=[('STANDARD', 'Standard (Quantité simple)'), ('WEIGHT', 'Poids (Demander le poids)'), ('PACK_COUNT', 'Conditionnement (Unités par carton)')], default='STANDARD', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='printing.unit')),
            ],
            options={
                'verbose_name': 'Unité',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Référence / SKU')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.category', verbose_name='Catégorie')),
                ('custom_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_products', to='printing.labeltemplate', verbose_name='Template spécifique (écrase celui de la catégorie)')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printing.unit', verbose_name='Unité de mesure')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du poste')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('allowed_categories', models.ManyToManyField(related_name='workstations', to='printing.category')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, unique=True)),
                ('recorded_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_pack_count', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_printed', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printing.labeltemplate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printing.product')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.workstation')),
            ],
        ),
    ]
