# Generated by Django 6.0.5 on 2026-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationImprimante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_poste', models.CharField(help_text='Ex: PC_LAPTOP, PC_BUREAU, PC_ATELIER_1. Doit correspondre au .env', max_length=50, unique=True)),
                ('nom_emplacement', models.CharField(help_text='Ex: Bureau de Yaniv, Ligne Conditionnement', max_length=100)),
                ('mode_connexion', models.CharField(choices=[('USB', 'Connexion USB (Locale)'), ('RESEAU', 'Connexion Réseau (IP)'), ('DESACTIVE', "Pas d'imprimante (Simulé / Mode Test)")], default='USB', max_length=15)),
                ('nom_systeme_windows', models.CharField(blank=True, default='ZDesigner ZM400 200 dpi (ZPL)', help_text="Nom exact de l'imprimante sous Windows (requis si mode USB)", max_length=255)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, default='192.168.100.200', null=True)),
                ('port_reseau', models.IntegerField(default=9100, help_text='Par défaut 9100 pour les Zebra')),
            ],
            options={
                'verbose_name': 'Configuration Imprimante Poste',
                'verbose_name_plural': 'Configuration Imprimantes Postes',
            },
        ),
    ]
