# Generated by Django 6.0.5 on 2026-07-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_configurationimprimante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('numero_client', models.CharField(max_length=50, unique=True, verbose_name='Numéro de client')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='printjob',
            options={'verbose_name': "Tâche d'impression", 'verbose_name_plural': "Tâches d'impression"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unité', 'verbose_name_plural': 'Unités'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'verbose_name': 'Poste de travail', 'verbose_name_plural': 'Postes de travail'},
        ),
        migrations.CreateModel(
            name='ImpressionEtiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_impression', models.DateTimeField(auto_now_add=True, verbose_name='Date & Heure')),
                ('code_poste', models.CharField(max_length=50, verbose_name='Code Poste / Machine')),
                ('ip_client', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Utilisateur')),
                ('produit_nom', models.CharField(max_length=255, verbose_name='Désignation Produit')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU / Réf')),
                ('client_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Client')),
                ('laize', models.CharField(blank=True, max_length=20, null=True, verbose_name='Laize (cm)')),
                ('micron', models.CharField(blank=True, max_length=20, null=True, verbose_name='Épaisseur (µm)')),
                ('quantite_valeur', models.CharField(max_length=50, verbose_name='Valeur (Poids / Pcs)')),
                ('unite', models.CharField(default='Kg', max_length=20, verbose_name='Unité')),
                ('colis_count', models.IntegerField(default=1, verbose_name='Nombre de Colis/Cartons')),
                ('labels_per_colis', models.IntegerField(default=1, verbose_name='Étiquettes par Colis')),
                ('total_etiquettes', models.IntegerField(default=1, verbose_name='Total Étiquettes Imprimées')),
                ('zpl_genere', models.TextField(blank=True, null=True, verbose_name='Code ZPL Généré')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_impressions', to='printing.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_impressions', to='printing.product')),
            ],
            options={
                'verbose_name': "Historique d'impression",
                'verbose_name_plural': 'Historique des impressions',
                'ordering': ['-date_impression'],
            },
        ),
    ]
