# Generated by Django 6.0.5 on 2026-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_client_alter_category_options_alter_printjob_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressionetiquette',
            name='colis_count',
        ),
        migrations.AddField(
            model_name='configurationimprimante',
            name='ip_poste_client',
            field=models.GenericIPAddressField(blank=True, help_text="Ex: 192.168.100.26 (L'IP du PC qui envoie la commande d'impression)", null=True, verbose_name='IP Poste Client (Navigateur)'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='colis_index',
            field=models.IntegerField(default=1, verbose_name='Colis N°'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='colis_total',
            field=models.IntegerField(default=1, verbose_name='Total Colis'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='numero_lot',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='N° de Lot'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='poids_brut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poids Brut'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='poids_net',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poids Net'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='qty_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Détail Qté/Pièces'),
        ),
        migrations.AddField(
            model_name='impressionetiquette',
            name='type_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Détail Type'),
        ),
        migrations.AlterField(
            model_name='configurationimprimante',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, default='192.168.100.37', help_text="Ex: 192.168.100.37 (L'IP du Pi sur lequel est branchée la Zebra)", null=True, verbose_name='IP Imprimante / Raspberry Pi'),
        ),
        migrations.AlterField(
            model_name='configurationimprimante',
            name='code_poste',
            field=models.CharField(help_text='Ex: PC_LAPTOP, PC_BUREAU, PC_EXTRUSION_1. Doit correspondre au .env', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationimprimante',
            name='mode_connexion',
            field=models.CharField(choices=[('USB', 'Connexion USB (Locale)'), ('RESEAU', 'Connexion Réseau (IP)'), ('DESACTIVE', "Pas d'imprimante (Simulé / Mode Test)")], default='RESEAU', max_length=15),
        ),
        migrations.AlterField(
            model_name='configurationimprimante',
            name='nom_emplacement',
            field=models.CharField(help_text='Ex: Bureau de Yaniv, Ligne Extrusion 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='impressionetiquette',
            name='code_poste',
            field=models.CharField(max_length=50, verbose_name='Code Poste'),
        ),
        migrations.AlterField(
            model_name='impressionetiquette',
            name='quantite_valeur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valeur (Poids / Pcs)'),
        ),
    ]
