# Generated by Django 6.0.5 on 2026-09-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_remove_impressionetiquette_colis_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressionetiquette',
            name='destination',
        ),
    ]
