# Generated by Django 6.0.5 on 2026-09-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0005_remove_impressionetiquette_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='label_templates', to='printing.category', verbose_name='Catégories compatibles'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Modèle par défaut global'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='printing.labeltemplate', verbose_name="Template d'impression par défaut"),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='printing.category', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Caractéristique')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unité (ex: cm, µm, mm, kg)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='printing.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Définition de caractéristique',
                'verbose_name_plural': 'Définitions de caractéristiques',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255, verbose_name='Valeur')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.attributedefinition', verbose_name='Caractéristique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='printing.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Caractéristique du produit',
                'verbose_name_plural': 'Caractéristiques du produit',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
