# Generated by Django 6.0.5 on 2026-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0006_alter_client_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('NUMBER', 'Nombre décimal ou entier (ex: 50, 42.5)'), ('INTEGER', 'Nombre entier strict (ex: 500, 12)'), ('TEXT', 'Texte libre (ex: Transparent, PEBD)'), ('BOOLEAN', 'Oui / Non')], default='NUMBER', max_length=20, verbose_name='Type de donnée'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la caractéristique'),
        ),
    ]
