# Generated by Django 6.0.5 on 2026-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0007_attributedefinition_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='options',
            field=models.CharField(blank=True, help_text='Pour les listes de choix, séparez par des virgules (ex: PEBD, PEHD, PP, CPP)', max_length=500, null=True, verbose_name='Options autorisées'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('NUMBER', 'Nombre décimal ou entier (ex: 50, 42.5)'), ('INTEGER', 'Nombre entier strict (ex: 500, 12)'), ('CHOICE', 'Liste déroulante / Choix fermé (défini dans options)'), ('TEXT', 'Texte libre'), ('BOOLEAN', 'Oui / Non')], default='NUMBER', max_length=20, verbose_name='Type de donnée'),
        ),
    ]
