# Generated by Django 6.0.5 on 2026-09-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('printing', '0008_attributedefinition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='category',
            name='default_template',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom_template',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AlterField(
            model_name='printjob',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='impressionetiquette',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_impressions', to='catalog.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unit',
            name='base_unit',
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='label_templates', to='catalog.category', verbose_name='Catégories compatibles'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='allowed_categories',
            field=models.ManyToManyField(related_name='workstations', to='catalog.category'),
        ),
        migrations.DeleteModel(
            name='AttributeDefinition',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
